apiVersion: "v1"
kind: "Service"
metadata:
  name: "rabbitmq-service"
spec:
  #clusterIP: None
  ports:
    -
      name: "rabbimq-server"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
      # nodePort: 0
    -
      name: "rabbimq-server-mgm"
      protocol: "TCP"
      port: 15672
      targetPort: 15672
      # nodePort: 0
  selector:
    app: rabbitmq
  type: LoadBalancer
---
apiVersion: "v1"
kind: "Endpoints"
metadata:
  name: "rabbitmq-endpoint"
subsets:
  -
    addresses:
      -
        ip: "10.128.0.27"
    ports:
      -
        port: 5672
        name: "rabbitmq-server"
      - 
        port: 15672
        name: "rabbitmq-mgm"