version: "3.9"
networks:
  asa-bridge:
    ipam:
      config:
        - subnet: 10.18.0.0/16

services:
  app:
    build: ./projeto/.
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=db
      - DB_PORT=5432

    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data



