version: "3.9"


services:
  app:
    build: ./projeto/.
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=db
      - DB_PORT=5432
      

    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=db
      - DB_PORT=5432
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
